/** Sign-in, onboarding and chakra strings. Bhojpuri and Maithili fall back to Hindi. */
export const AUTH_UI: Record<string, Record<string, string>> = {
  bn: {
    homeTitle: 'আপনার খামার, এক চক্রে',
    homeLead: 'প্রতিটি কাজ কয়েকটি সহজ ধাপে। প্রতিটি উত্তর প্রকাশিত সূত্র থেকে।',
    start: 'শুরু করুন',
    signIn: 'সাইন ইন',
    signOut: 'সাইন আউট',
    register: 'খামার নথিভুক্ত করুন',
    haveKey: 'টেন্যান্ট কী আছে?',
    noKey: 'কী নেই?',
    tenantKey: 'টেন্যান্ট কী',
    username: 'ইউজারনেম',
    waking: 'সার্ভার চালু হচ্ছে… এক মিনিট অপেক্ষা করুন',
    loginFail: 'টেন্যান্ট কী বা ইউজারনেম ঠিক নয়।',
    netFail: 'সার্ভারে পৌঁছানো যায়নি। আবার চেষ্টা করুন।',
    farm: 'খামারের নাম',
    owner: 'আপনার নাম',
    phone: 'ফোন নম্বর',
    email: 'ইমেল (ঐচ্ছিক)',
    district: 'জেলা',
    sendRequest: 'অনুরোধ পাঠান',
    requestSent: 'অনুরোধ পাওয়া গেছে',
    requestSentHint: 'অনুমোদনের পর আপনি টেন্যান্ট কী আর ইউজারনেম পাবেন, সঙ্গে এক-ক্লিক সাইন-ইন লিংক।',
    howItWorks: 'কীভাবে কাজ করে',
    steps: 'ধাপ',
    farmOf: 'খামার',
    accessTitle: 'খামারের প্রবেশাধিকার',
    'access.1': 'নথিভুক্ত করুন', 'access.1h': 'খামারের নাম আর ফোন দিন',
    'access.2': 'অনুমোদন', 'access.2h': 'Poultry 360 আপনার অনুরোধ দেখে',
    'access.3': 'কী পান', 'access.3h': 'টেন্যান্ট কী আর ইউজারনেম, লিংকসহ',
    'access.4': 'সাইন ইন', 'access.4h': 'এক ক্লিকে, ৭ দিন মনে থাকে',
    'count.1': 'ছবি বা ভিডিও', 'count.1h': 'শেডের ছবি তুলুন',
    'count.2': 'AI গোনে', 'count.2h': 'প্রতিটি পাখির চারপাশে বাক্স',
    'count.3': 'চোখে মিলিয়ে নিন', 'count.3h': 'ভুল হলে সংখ্যা ঠিক করুন',
    'count.4': 'রেকর্ড', 'count.4h': 'আপনার নিশ্চিত সংখ্যাই রাখা হয়',
    'feed.1': 'বয়স', 'feed.1h': 'মুরগির বয়স দিনে',
    'feed.2': 'সংখ্যা', 'feed.2h': 'কতগুলি পাখি',
    'feed.3': 'প্রকাশিত তালিকা', 'feed.3h': 'পুষ্টির মান সূত্রসহ',
    'feed.4': 'আজকের খাবার', 'feed.4h': 'মোট কেজি আজ',
    'health.1': 'লক্ষণ বাছুন', 'health.1h': 'যা চোখে দেখছেন',
    'health.2': 'নির্দেশিকা', 'health.2h': 'সাধারণ পরামর্শ, রোগনির্ণয় নয়',
    'health.3': 'পশু চিকিৎসক', 'health.3h': 'গুরুতর হলে ডাক্তার ডাকুন',
  },
  hi: {
    homeTitle: 'आपका फ़ार्म, एक चक्र में',
    homeLead: 'हर काम कुछ आसान कदमों में। हर जवाब प्रकाशित स्रोत से।',
    start: 'शुरू करें',
    signIn: 'साइन इन',
    signOut: 'साइन आउट',
    register: 'फ़ार्म रजिस्टर करें',
    haveKey: 'टेनेंट की है?',
    noKey: 'की नहीं है?',
    tenantKey: 'टेनेंट की',
    username: 'यूज़रनेम',
    waking: 'सर्वर चालू हो रहा है… एक मिनट रुकें',
    loginFail: 'टेनेंट की या यूज़रनेम सही नहीं है।',
    netFail: 'सर्वर तक नहीं पहुँच पाए। फिर कोशिश करें।',
    farm: 'फ़ार्म का नाम',
    owner: 'आपका नाम',
    phone: 'फ़ोन नंबर',
    email: 'ईमेल (वैकल्पिक)',
    district: 'ज़िला',
    sendRequest: 'अनुरोध भेजें',
    requestSent: 'अनुरोध मिल गया',
    requestSentHint: 'मंज़ूरी के बाद आपको टेनेंट की और यूज़रनेम मिलेगा, साथ में एक-क्लिक साइन-इन लिंक।',
    howItWorks: 'कैसे काम करता है',
    steps: 'कदम',
    farmOf: 'फ़ार्म',
    accessTitle: 'फ़ार्म की पहुँच',
    'access.1': 'रजिस्टर करें', 'access.1h': 'फ़ार्म का नाम और फ़ोन दें',
    'access.2': 'मंज़ूरी', 'access.2h': 'Poultry 360 आपका अनुरोध देखता है',
    'access.3': 'की पाएँ', 'access.3h': 'टेनेंट की और यूज़रनेम, लिंक के साथ',
    'access.4': 'साइन इन', 'access.4h': 'एक क्लिक में, 7 दिन याद रहता है',
    'count.1': 'फ़ोटो या वीडियो', 'count.1h': 'शेड की फ़ोटो लें',
    'count.2': 'AI गिनता है', 'count.2h': 'हर पक्षी पर एक बॉक्स',
    'count.3': 'आँख से जाँचें', 'count.3h': 'गलत हो तो संख्या सुधारें',
    'count.4': 'दर्ज करें', 'count.4h': 'आपकी पक्की संख्या ही रखी जाती है',
    'feed.1': 'उम्र', 'feed.1h': 'मुर्गी की उम्र दिनों में',
    'feed.2': 'संख्या', 'feed.2h': 'कितनी मुर्गियाँ',
    'feed.3': 'प्रकाशित तालिका', 'feed.3h': 'पोषण मान, स्रोत के साथ',
    'feed.4': 'आज का दाना', 'feed.4h': 'आज कुल कितने किलो',
    'health.1': 'लक्षण चुनें', 'health.1h': 'जो आँख से दिख रहा है',
    'health.2': 'मार्गदर्शन', 'health.2h': 'सामान्य सलाह, निदान नहीं',
    'health.3': 'पशु डॉक्टर', 'health.3h': 'गंभीर हो तो डॉक्टर बुलाएँ',
  },
  en: {
    homeTitle: 'Your farm, in one chakra',
    homeLead: 'Every job in a few simple steps. Every answer from a cited source.',
    start: 'Start',
    signIn: 'Sign in',
    signOut: 'Sign out',
    register: 'Register your farm',
    haveKey: 'Have a tenant key?',
    noKey: 'No key yet?',
    tenantKey: 'Tenant key',
    username: 'Username',
    waking: 'Starting the server… please wait a minute',
    loginFail: 'Tenant key or username is not right.',
    netFail: 'Could not reach the server. Please try again.',
    farm: 'Farm name',
    owner: 'Your name',
    phone: 'Phone number',
    email: 'Email (optional)',
    district: 'District',
    sendRequest: 'Send request',
    requestSent: 'Request received',
    requestSentHint: 'Once approved you get a tenant key and username, with a one-click sign-in link.',
    howItWorks: 'How it works',
    steps: 'steps',
    farmOf: 'Farm',
    accessTitle: 'Farm access',
    'access.1': 'Register', 'access.1h': 'Farm name and phone',
    'access.2': 'Approval', 'access.2h': 'Poultry 360 reviews your request',
    'access.3': 'Get your key', 'access.3h': 'Tenant key and username, with a link',
    'access.4': 'Sign in', 'access.4h': 'One click, remembered for 7 days',
    'count.1': 'Photo or video', 'count.1h': 'Photograph the shed',
    'count.2': 'AI counts', 'count.2h': 'A box around every bird',
    'count.3': 'Check by eye', 'count.3h': 'Fix the number if it is wrong',
    'count.4': 'Record', 'count.4h': 'Your confirmed number is kept',
    'feed.1': 'Age', 'feed.1h': 'Bird age in days',
    'feed.2': 'Birds', 'feed.2h': 'How many birds',
    'feed.3': 'Published table', 'feed.3h': 'Nutrient values with sources',
    'feed.4': 'Feed today', 'feed.4h': 'Total kilograms today',
    'health.1': 'Pick the signs', 'health.1h': 'What you can see',
    'health.2': 'Guidance', 'health.2h': 'General advice, not a diagnosis',
    'health.3': 'Vet', 'health.3h': 'Call a vet if it is serious',
  },
};

export const FLOW_ICONS: Record<string, string[]> = {
  access: ['📝', '✅', '🔑', '🚪'],
  count: ['📷', '🤖', '👀', '📒'],
  feed: ['🐣', '🐔', '📊', '🌾'],
  health: ['☑️', '📖', '🩺'],
};
