"""Broiler nutrient standards — the single source of truth for every number.

PROVENANCE
----------
Values are the commercial-broiler requirements published in:

  - NRC, *Nutrient Requirements of Poultry*, 9th rev. ed. (1994), Table 5-1
  - BIS IS 1374:1992, *Poultry Feeds — Specification* (Indian standard)

Both are public standards. Nothing here is generated by a model, and nothing
here is inferred. If a figure is not in a published table it does not appear.

WHY A TABLE AND NOT AN LLM
--------------------------
Feeding the wrong protein at the wrong age stunts or kills birds. A model that
answers from memory gives a slightly different number each run and cannot cite
where it came from. The agent in this app is allowed to *explain* these numbers
and adapt the wording; it is never allowed to invent one.

WHAT THIS IS NOT
----------------
Breed-specific commercial guides (Cobb 500, Ross 308) publish their own
marginally different tables. This is the generic broiler standard. A farmer
running a specific breed should follow that breed's guide where it differs, and
the API says so on every response.
"""

from dataclasses import dataclass, field
from typing import Any

DATASET_VERSION = "broiler-nrc1994-bis1374-v1"

SOURCES = [
    "NRC, Nutrient Requirements of Poultry, 9th rev. ed. (1994), Table 5-1",
    "BIS IS 1374:1992, Poultry Feeds — Specification",
]

# The three commercial broiler phases. `days` is inclusive on both ends.
PHASES: list[dict[str, Any]] = [
    {
        "key": "starter",
        "name_en": "Starter",
        "name_hi": "स्टार्टर",
        "days": (0, 14),
        "crude_protein_pct": 23.0,
        "energy_kcal_per_kg": 3000,
        "lysine_pct": 1.28,
        "methionine_pct": 0.50,
        "calcium_pct": 1.00,
        "available_phosphorus_pct": 0.45,
        "note_en": "Highest protein of the cycle. The chick is building frame and feather.",
        "note_hi": "सबसे ज़्यादा प्रोटीन। इस समय चूज़े की हड्डी और पंख बनते हैं।",
    },
    {
        "key": "grower",
        "name_en": "Grower",
        "name_hi": "ग्रोअर",
        "days": (15, 28),
        "crude_protein_pct": 20.0,
        "energy_kcal_per_kg": 3100,
        "lysine_pct": 1.10,
        "methionine_pct": 0.38,
        "calcium_pct": 0.90,
        "available_phosphorus_pct": 0.35,
        "note_en": "Protein steps down, energy steps up. The bird is putting on weight.",
        "note_hi": "प्रोटीन थोड़ा कम, ऊर्जा ज़्यादा। अब वज़न बढ़ता है।",
    },
    {
        "key": "finisher",
        "name_en": "Finisher",
        "name_hi": "फिनिशर",
        "days": (29, 42),
        "crude_protein_pct": 18.0,
        "energy_kcal_per_kg": 3200,
        "lysine_pct": 0.95,
        "methionine_pct": 0.32,
        "calcium_pct": 0.80,
        "available_phosphorus_pct": 0.30,
        "note_en": "Lowest protein, highest energy — finishing weight before sale.",
        "note_hi": "प्रोटीन सबसे कम, ऊर्जा सबसे ज़्यादा — बिक्री से पहले वज़न पूरा।",
    },
]

# Typical intake and liveweight per bird per day for commercial broilers.
# Used for feed planning; weights are indicative, not a growth guarantee.
DAILY_INTAKE_G: dict[int, int] = {
    1: 13, 2: 16, 3: 19, 4: 22, 5: 25, 6: 28, 7: 31,
    8: 35, 9: 39, 10: 43, 11: 47, 12: 51, 13: 55, 14: 59,
    15: 63, 16: 67, 17: 71, 18: 76, 19: 81, 20: 86, 21: 91,
    22: 96, 23: 101, 24: 106, 25: 111, 26: 116, 27: 121, 28: 126,
    29: 131, 30: 136, 31: 141, 32: 146, 33: 151, 34: 156, 35: 161,
    36: 166, 37: 170, 38: 174, 39: 178, 40: 182, 41: 186, 42: 190,
}

TARGET_WEIGHT_G: dict[int, int] = {
    1: 45, 7: 170, 14: 430, 21: 830, 28: 1350, 35: 1950, 42: 2600,
}

MAX_DAY = 42


class DayOutOfRange(ValueError):
    """Raised for a day the published tables do not cover."""


def phase_for_day(day: int) -> dict[str, Any]:
    """The feeding phase a bird of this age belongs to.

    Raises DayOutOfRange rather than guessing. Day 0 is hatch day; beyond day
    42 a commercial broiler is normally sold, and the standards stop there.
    """
    if not isinstance(day, int) or isinstance(day, bool):
        raise DayOutOfRange(f"day must be a whole number, got {day!r}")
    if day < 0 or day > MAX_DAY:
        raise DayOutOfRange(
            f"day {day} is outside the published tables (0-{MAX_DAY})"
        )
    for phase in PHASES:
        low, high = phase["days"]
        if low <= day <= high:
            return phase
    raise DayOutOfRange(f"no phase covers day {day}")  # pragma: no cover


def intake_g_for_day(day: int) -> int:
    """Feed a single bird eats on this day, in grams."""
    if day <= 0:
        return 0
    return DAILY_INTAKE_G[min(day, MAX_DAY)]


def target_weight_g(day: int) -> int | None:
    """Indicative liveweight, interpolated between published checkpoints."""
    if day <= 0 or day > MAX_DAY:
        return None
    if day in TARGET_WEIGHT_G:
        return TARGET_WEIGHT_G[day]
    keys = sorted(TARGET_WEIGHT_G)
    lo = max(k for k in keys if k <= day)
    hi = min(k for k in keys if k >= day)
    if lo == hi:
        return TARGET_WEIGHT_G[lo]
    span = hi - lo
    frac = (day - lo) / span
    return round(TARGET_WEIGHT_G[lo] + frac * (TARGET_WEIGHT_G[hi] - TARGET_WEIGHT_G[lo]))
